/**
 *  * ブランドアカウント対応 - チャンネル診断・修正用関数
  * 問題: mine:true が個人チャンネルを返すため、ブランドチャンネルのAnalyticsが取得できない
   * 解決: managedByMe:true でブランドチャンネル一覧を取得し、正しいチャンネルIDを使用
    */

    /**
     * 診断: 現在のOAuth状態でアクセスできるチャンネル一覧を表示
      */
      function diagnoseManagedChannels() {
        Logger.log('=== チャンネル診断開始 ===');
          
            // 1. mine:true で返されるチャンネル（現在の問題）
              Logger.log('');
                Logger.log('【1】mine:true で返されるチャンネル:');
                  try {
                      var mineResponse = YouTube.Channels.list('snippet,statistics', { mine: true });
                          if (mineResponse.items && mineResponse.items.length > 0) {
                                mineResponse.items.forEach(function(ch) {
                                        Logger.log('  ID: ' + ch.id);
                                                Logger.log('  名前: ' + ch.snippet.title);
                                                        Logger.log('  登録者: ' + ch.statistics.subscriberCount);
                                                              });
                                                                  } else {
                                                                        Logger.log('  チャンネルなし');
                                                                            }
                                                                              } catch (e) {
                                                                                  Logger.log('  エラー: ' + e.message);
                                                                                    }
                                                                                      
                                                                                        // 2. managedByMe:true で返されるチャンネル（ブランドチャンネル含む）
                                                                                          Logger.log('');
                                                                                            Logger.log('【2】managedByMe:true で返されるチャンネル:');
                                                                                              try {
                                                                                                  var managedResponse = YouTube.Channels.list('snippet,statistics', { managedByMe: true });
                                                                                                      if (managedResponse.items && managedResponse.items.length > 0) {
                                                                                                            managedResponse.items.forEach(function(ch) {
                                                                                                                    Logger.log('  ID: ' + ch.id);
                                                                                                                            Logger.log('  名前: ' + ch.snippet.title);
                                                                                                                                    Logger.log('  登録者: ' + ch.statistics.subscriberCount);
                                                                                                                                            Logger.log('  ---');
                                                                                                                                                  });
                                                                                                                                                      } else {
                                                                                                                                                            Logger.log('  チャンネルなし');
                                                                                                                                                                }
                                                                                                                                                                  } catch (e) {
                                                                                                                                                                      Logger.log('  エラー: ' + e.message);
                                                                                                                                                                        }
                                                                                                                                                                          
                                                                                                                                                                            // 3. ターゲットのブランドチャンネル情報
                                                                                                                                                                              var brandChannelId = 'YOUTUBE_CHANNEL_ID_PLACEHOLDER';
                                                                                                                                                                                Logger.log('');
                                                                                                                                                                                  Logger.log('【3】ターゲットブランドチャンネル:');
                                                                                                                                                                                    Logger.log('  ID: ' + brandChannelId);
                                                                                                                                                                                      try {
                                                                                                                                                                                          var brandResponse = YouTube.Channels.list('snippet,statistics', { id: brandChannelId });
                                                                                                                                                                                              if (brandResponse.items && brandResponse.items.length > 0) {
                                                                                                                                                                                                    var ch = brandResponse.items[0];
                                                                                                                                                                                                          Logger.log('  名前: ' + ch.snippet.title);
                                                                                                                                                                                                                Logger.log('  登録者: ' + ch.statistics.subscriberCount);
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                          Logger.log('  エラー: ' + e.message);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                Logger.log('');
                                                                                                                                                                                                                                  Logger.log('=== 診断終了 ===');
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                   * ブランドチャンネルIDを使ってAnalytics APIをテスト
                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                    function testAnalyticsWithBrandChannel() {
                                                                                                                                                                                                                                      var brandChannelId = 'YOUTUBE_CHANNEL_ID_PLACEHOLDER';
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          Logger.log('=== ブランドチャンネルでAnalyticsテスト ===');
                                                                                                                                                                                                                                            Logger.log('チャンネルID: ' + brandChannelId);
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                var endDate = new Date();
                                                                                                                                                                                                                                                  var startDate = new Date();
                                                                                                                                                                                                                                                    startDate.setDate(startDate.getDate() - 28);
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        var startDateStr = Utilities.formatDate(startDate, 'Asia/Tokyo', 'yyyy-MM-dd');
                                                                                                                                                                                                                                                          var endDateStr = Utilities.formatDate(endDate, 'Asia/Tokyo', 'yyyy-MM-dd');
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              Logger.log('期間: ' + startDateStr + ' ～ ' + endDateStr);
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                      // channel==CHANNEL_ID 形式で直接指定
                                                                                                                                                                                                                                                                          var response = YouTubeAnalytics.Reports.query({
                                                                                                                                                                                                                                                                                ids: 'channel==' + brandChannelId,
                                                                                                                                                                                                                                                                                      startDate: startDateStr,
                                                                                                                                                                                                                                                                                            endDate: endDateStr,
                                                                                                                                                                                                                                                                                                  metrics: 'views,estimatedMinutesWatched,averageViewDuration',
                                                                                                                                                                                                                                                                                                        dimensions: 'video',
                                                                                                                                                                                                                                                                                                              maxResults: 10,
                                                                                                                                                                                                                                                                                                                    sort: '-views'
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                Logger.log('API成功！');
                                                                                                                                                                                                                                                                                                                                    Logger.log('行数: ' + (response.rows ? response.rows.length : 0));
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            if (response.rows && response.rows.length > 0) {
                                                                                                                                                                                                                                                                                                                                                  Logger.log('');
                                                                                                                                                                                                                                                                                                                                                        Logger.log('トップ動画:');
                                                                                                                                                                                                                                                                                                                                                              response.rows.forEach(function(row, i) {
                                                                                                                                                                                                                                                                                                                                                                      Logger.log((i+1) + '. 動画ID: ' + row[0] + ', 再生: ' + row[1] + ', 平均視聴: ' + Math.round(row[3]) + '秒');
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                      Logger.log('データなし - 権限の問題の可能性があります');
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                    Logger.log('エラー: ' + e.message);
                                                                                                                                                                                                                                                                                                                                                                                                        if (e.message.indexOf('forbidden') !== -1 || e.message.indexOf('403') !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                              Logger.log('');
                                                                                                                                                                                                                                                                                                                                                                                                                    Logger.log('【解決方法】');
                                                                                                                                                                                                                                                                                                                                                                                                                          Logger.log('このエラーは、現在のOAuth認証がブランドチャンネルの所有者として認識されていないことを示します。');
                                                                                                                                                                                                                                                                                                                                                                                                                                Logger.log('以下を確認してください:');
                                                                                                                                                                                                                                                                                                                                                                                                                                      Logger.log('1. Google Cloud ConsoleでYouTube Analytics APIが有効になっているか');
                                                                                                                                                                                                                                                                                                                                                                                                                                            Logger.log('2. 実行ユーザーがブランドチャンネルのOwner権限を持っているか');
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Logger.log('3. 認証をリセット(resetAuth)してから、再度実行してみてください');
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Logger.log('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Logger.log('=== テスト終了 ===');
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
 